# Generated by Django 3.2.4 on 2024-05-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Primer plato', 'Primer plato'), ('Segundo plato', 'Segundo plato'), ('Postre', 'Postre'), ('Bebida', 'Bebida')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='menu_semanal/')),
                ('descripcion', models.TextField(blank=True)),
                ('menu_semanal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menusemanal')),
            ],
        ),
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plato')),
            ],
        ),
    ]
